### ISSUE TITLE
Possibly Corrupted "point_history_classifier.tflite" File

### ISSUE THREAD

**Issue by Eli-Murphy** [kinivi/tello-gesture-control#10]
Hey,
I am trying to run main.py but keep getting "ValueError: Could not open 'model/point_history_classifier/point_history_classifier.tflite'." I am thinking it could be corrupted. Could you check that out?
Thanks!

**Comment by kinivi** [comment]
Hi, 

'model/point_history_classifier/point_history_classifier.tflite' - is an LSTM model and unfortunately I didn't integrate it into this project. You can try to retrain it using notebook from [ this repo ](https://github.com/kinivi/hand-gesture-recognition-mediapipe) or the [original](https://github.com/Kazuhito00/hand-gesture-recognition-using-mediapipe) one. Pls let me know if you will still have problems.

**Comment by hengjiUSTC** [comment]
Hi, 
Instead of retraining, is there any place we can download point_history_classifier.tflite directly?

**Comment by kinivi** [comment]
I suppose you can use it from here https://github.com/Kazuhito00/hand-gesture-recognition-using-mediapipe

**Comment by kinivi** [comment]
But I didn't integrate it with drone control, still it is feasible to do

**Comment by hengjiUSTC** [comment]
Thanks, it works well.
