### ISSUE TITLE
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

### ISSUE THREAD

**Issue by jaggu96525** [kinivi/tello-gesture-control#14]
I installed all the requirement as given once run the it shows (Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.) this type of error please explain it sir

**Comment by kinivi** [comment]
I haven't tested on Windows. Probably, try to use Linux on windows or Emulator. This will help a lot also in the dependency installation.

**Comment by jaggu96525** [comment]
sir thank you for this response
