### ISSUE TITLE
It doesn't work in my Mac enviroment

### ISSUE THREAD

**Issue by vitorcalvi** [kinivi/tello-gesture-control#17]
As follow python commands output:

python3 tests/connection_test.py
1. Connection test:
[INFO] tello.py - 129 - Tello instance was initialized. Host: '192.168.1.142'. Port: '8889'.
[INFO] tello.py - 438 - Send command: 'command'
[INFO] tello.py - 462 - Response command: 'ok'

2. Video stream test:
[INFO] tello.py - 438 - Send command: 'streamon'
[INFO] tello.py - 462 - Response streamon: 'ok'

[INFO] tello.py - 438 - Send command: 'streamoff'
[INFO] tello.py - 462 - Response streamoff: 'ok'

---------------------------------------------------

python3 main.py
## Reading configuration ##
[INFO] tello.py - 129 - Tello instance was initialized. Host: '192.168.1.142'. Port: '8889'.
[INFO] tello.py - 438 - Send command: 'command'
[INFO] tello.py - 462 - Response command: 'ok'
[INFO] tello.py - 438 - Send command: 'streamon'
[INFO] tello.py - 462 - Response streamon: 'ok'
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1702369536.445340       1 gl_context.cc:344] GL version: 2.1 (2.1 Metal - 88), renderer: Apple M2 Max
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
[INFO] tello.py - 438 - Send command: 'down 20'
No accelerated colorspace conversion found from yuv420p to rgb24.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
[INFO] tello.py - 462 - Response down 20: 'error Motor stop'
[INFO] tello.py - 438 - Send command: 'down 20'
[INFO] tello.py - 462 - Response down 20: 'error Motor stop'
[INFO] tello.py - 438 - Send command: 'down 20'
[INFO] tello.py - 462 - Response down 20: 'error Motor stop'
Traceback (most recent call last):
  File "main.py", line 163, in <module>
    main()
  File "main.py", line 103, in main
    tello.move_down(20)
  File "/opt/homebrew/anaconda3/envs/tello2/lib/python3.8/site-packages/djitellopy/enforce_types.py", line 54, in wrapper
    return func(*args, **kwargs)
  File "/opt/homebrew/anaconda3/envs/tello2/lib/python3.8/site-packages/djitellopy/tello.py", line 635, in move_down
    self.move("down", x)
  File "/opt/homebrew/anaconda3/envs/tello2/lib/python3.8/site-packages/djitellopy/enforce_types.py", line 54, in wrapper
    return func(*args, **kwargs)
  File "/opt/homebrew/anaconda3/envs/tello2/lib/python3.8/site-packages/djitellopy/tello.py", line 621, in move
    self.send_control_command("{} {}".format(direction, x))
  File "/opt/homebrew/anaconda3/envs/tello2/lib/python3.8/site-packages/djitellopy/enforce_types.py", line 54, in wrapper
    return func(*args, **kwargs)
  File "/opt/homebrew/anaconda3/envs/tello2/lib/python3.8/site-packages/djitellopy/tello.py", line 487, in send_control_command
    self.raise_result_error(command, response)
  File "/opt/homebrew/anaconda3/envs/tello2/lib/python3.8/site-packages/djitellopy/enforce_types.py", line 54, in wrapper
    return func(*args, **kwargs)
  File "/opt/homebrew/anaconda3/envs/tello2/lib/python3.8/site-packages/djitellopy/tello.py", line 529, in raise_result_error
    raise TelloException("Command '{}' was unsuccessful for {} tries. Latest response:\t'{}'"
djitellopy.tello.TelloException: Command 'down 20' was unsuccessful for 4 tries. Latest response:	'error Motor stop'
[INFO] tello.py - 438 - Send command: 'streamoff'
[WARNING] tello.py - 448 - Aborting command 'streamoff'. Did not receive a response after 7 seconds
[INFO] tello.py - 438 - Send command: 'streamoff'
[WARNING] tello.py - 448 - Aborting command 'streamoff'. Did not receive a response after 7 seconds
[INFO] tello.py - 438 - Send command: 'streamoff'
[WARNING] tello.py - 448 - Aborting command 'streamoff'. Did not receive a response after 7 seconds

**Comment by kinivi** [comment]
Seems like empty command. Did you change the package versioning? I can see that you are using Python 3.8

**Comment by vitorcalvi** [comment]
@kinivi didn't change the package version. Put it in python 3.7. Logging as follow

python3 --version
Python 3.7.12
❯ python3 tests/tello_test.py
[INFO] tello.py - 129 - Tello instance was initialized. Host: '192.168.1.146'. Port: '8889'.
[INFO] tello.py - 438 - Send command: 'command'
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
[INFO] tello.py - 462 - Response command: 'ok'
[INFO] tello.py - 438 - Send command: 'streamon'
[INFO] tello.py - 462 - Response streamon: 'ok'

❯ python3 main.py
[1]    60008 illegal hardware instruction  python3 main.py

**Comment by vitorcalvi** [comment]
> @kinivi didn't change the package version. Put it in python 3.7. Logging as follow
> 
> python3 --version Python 3.7.12 ❯ python3 tests/tello_test.py [INFO] tello.py - 129 - Tello instance was initialized. Host: '192.168.1.146'. Port: '8889'. [INFO] tello.py - 438 - Send command: 'command' INFO: Created TensorFlow Lite XNNPACK delegate for CPU. [INFO] tello.py - 462 - Response command: 'ok' [INFO] tello.py - 438 - Send command: 'streamon' [INFO] tello.py - 462 - Response streamon: 'ok'
> 
> ❯ python3 main.py [1] 60008 illegal hardware instruction python3 main.py
