### ISSUE TITLE
Regarding Run time / tello-gesture-control/running/ main.py

### ISSUE THREAD

**Issue by drsharmamayank** [kinivi/tello-gesture-control#2]
## Reading configuration ##
usage: ipykernel_launcher.py [-h] [-c MY_CONFIG] [--device DEVICE]
                             [--width WIDTH] [--height HEIGHT]
                             [--is_keyboard IS_KEYBOARD]
                             [--use_static_image_mode]
                             [--min_detection_confidence MIN_DETECTION_CONFIDENCE]
                             [--min_tracking_confidence MIN_TRACKING_CONFIDENCE]
                             [--buffer_len BUFFER_LEN]
ipykernel_launcher.py: error: unrecognized arguments: -f C:\Users\mayank\AppData\Roaming\jupyter\runtime\kernel-97c73e9e-2e91-4deb-9b71-3f6e8e7a2fca.json
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

**Comment by kinivi** [comment]
Please, provide more details. What are you trying to run?
