### ISSUE TITLE
Incorrect number of initial gesture types

### ISSUE THREAD

**Issue by JwoolardAU** [kinivi/tello-gesture-control#7]
In README.md in the **_Creating dataset with new gestures_** section @kinivi  put "In the initial state, 7 types of learning data are included as was shown [here](https://github.com/kinivi/tello-gesture-control#Gesture-control)." Am I misunderstanding or is this just a simple typo and it should say "8 types"?

**Comment by kinivi** [comment]
Yes, it should be 8, thanks for pointing out!
