### ISSUE TITLE
Point History Classifier

### ISSUE THREAD

**Issue by Mohammad-Asad-110** [kinivi/tello-gesture-control#9]
Hey, I was unable to understand the use of the point history classifier, can you please shed light on it.

**Comment by kinivi** [comment]
Its an LSTM model that should classify gestures based on the history from the several frames. But unfortunately,  I didn't integrate it into this repo :( You can check this [repo](https://github.com/Kazuhito00/hand-gesture-recognition-using-mediapipe)
